const EXPLICIT_TOKEN_ALIASES: Readonly<Record<string, string>> = {
  affiliates: 'affiliate',
  agencies: 'agency',
  applications: 'application',
  appointments: 'appointment',
  approvals: 'approval',
  apps: 'app',
  apis: 'api',
  authorities: 'authority',
  backlinks: 'backlink',
  banks: 'bank',
  botnets: 'botnet',
  bookings: 'booking',
  bonuses: 'bonus',
  cams: 'cam',
  cards: 'card',
  casinos: 'casino',
  clinics: 'clinic',
  communities: 'community',
  consumers: 'consumer',
  credentials: 'credential',
  credits: 'credit',
  cures: 'cure',
  deliveries: 'delivery',
  detectors: 'detector',
  dispensaries: 'dispensary',
  docs: 'documentation',
  documents: 'document',
  domains: 'domain',
  downloads: 'download',
  essays: 'essay',
  escorts: 'escort',
  exchanges: 'exchange',
  farms: 'farm',
  firearms: 'firearm',
  games: 'game',
  guides: 'guide',
  hospitals: 'hospital',
  ids: 'id',
  identities: 'identity',
  institutions: 'institution',
  investments: 'investment',
  kits: 'kit',
  libraries: 'library',
  links: 'link',
  loans: 'loan',
  manipulations: 'manipulation',
  marketplaces: 'marketplace',
  matches: 'match',
  networks: 'network',
  packages: 'package',
  patients: 'patient',
  payments: 'payment',
  pharmacies: 'pharmacy',
  platforms: 'platform',
  products: 'product',
  providers: 'provider',
  rentals: 'rental',
  reviews: 'review',
  rankings: 'ranking',
  sdks: 'sdk',
  services: 'service',
  shops: 'shop',
  sites: 'site',
  stealers: 'stealer',
  stores: 'store',
  studios: 'studio',
  tables: 'table',
  tooling: 'tool',
  tools: 'tool',
  verifications: 'verification',
  videos: 'video',
  websites: 'website'
}
const TOKEN_ALIAS_PATTERN = new RegExp(
  `\\b(?:${Object.keys(EXPLICIT_TOKEN_ALIASES).join('|')})\\b`,
  'gu'
)

/** Returns the explicit canonical form used for editorial token comparisons. */
export const canonicalEditorialToken = (token: string): string =>
  EXPLICIT_TOKEN_ALIASES[token] ?? token

/** Canonicalizes only the bounded, explicitly enumerated editorial token aliases. */
export const canonicalizeEditorialTokens = (text: string): string =>
  text.replace(TOKEN_ALIAS_PATTERN, token => canonicalEditorialToken(token))
