import { describe, expect, it } from 'vitest'
import { classifyLlmsTextBody } from './llms-content-classifier.js'

const DOCUMENT = `# Documentation

> Guides for developers building and maintaining software, with API references and tutorials for common integration tasks.

- [API documentation](https://example.com/docs)
`

describe('generated Markdown comments', () => {
  it('accepts a generated-file comment in otherwise meaningful Markdown', () => {
    expect(
      classifyLlmsTextBody(
        `${DOCUMENT}\n<!-- This file is automatically generated. Do not edit manually. -->`
      )
    ).toBe('high_confidence')
  })

  it('does not count comments as meaningful document content', () => {
    expect(
      classifyLlmsTextBody(`<!-- # Documentation https://example.com ${'hidden '.repeat(30)}-->`)
    ).toBe('invalid')
  })

  it('still rejects HTML following a comment', () => {
    expect(classifyLlmsTextBody(`${DOCUMENT}\n<!-- generated --><script>alert(1)</script>`)).toBe(
      'invalid'
    )
  })
})
